### ISSUE TITLE
Fails to compile due to warnings on GCC 9.2.0

### ISSUE THREAD

**Issue by CodyRude** [drpatrik/combatris#2]
Using Arch Linux with GCC 9.2.0 I get compiler warnings. Since these are treated as a errors it cancels the compilation. Removing -Werror from the compile flags allows the game to be compiled (with warnings). 

**Edit:** The code formatting doesn't seem to work very well. Here are the warnings on pastebin: https://pastebin.com/E6Mjez0w

`[19/63] Building CXX object combatris/CMakeFiles/combatris.dir/src/network/udp_client_server.cpp.o
FAILED: combatris/CMakeFiles/combatris.dir/src/network/udp_client_server.cpp.o 
/usr/bin/c++  -DASSETS_FOLDER=\"/data1/Games/combatris/combatris/assets/\" -I/usr/include/SDL2 -I../combatris/combatris -I../combatris/src -I../external/catch/src/catch/single_include/catch2 -Wall -Wextra -Werror -pedantic -std=c++1z  -Wall -Wextra -Werror -pedantic -std=c++1z -g -g -MD -MT combatris/CMakeFiles/combatris.dir/src/network/udp_client_server.cpp.o -MF combatris/CMakeFiles/combatris.dir/src/network/udp_client_server.cpp.o.d -o combatris/CMakeFiles/combatris.dir/src/network/udp_client_server.cpp.o -c ../combatris/src/network/udp_client_server.cpp
../combatris/src/network/udp_client_server.cpp: In member function ‘ssize_t network::UDPServer::Receive(void*, size_t, int)’:
../combatris/src/network/udp_client_server.cpp:259:42: error: passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
  259 |   const auto ret_val(select(socket_ + 1, &fds, nullptr, &fds, &timeout));
      |                                          ^~~~           ~~~~
../combatris/src/network/udp_client_server.cpp: In member function ‘ssize_t network::UDPServer::Receive(void*, size_t, sockaddr_in&, int)’:
../combatris/src/network/udp_client_server.cpp:285:42: error: passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
  285 |   const auto ret_val(select(socket_ + 1, &fds, nullptr, &fds, &timeout));
      |                                          ^~~~           ~~~~
cc1plus: all warnings being treated as errors
[22/63] Building CXX object combatris/CMakeFiles/combatris.dir/src/combatris.cpp.o
FAILED: combatris/CMakeFiles/combatris.dir/src/combatris.cpp.o 
/usr/bin/c++  -DASSETS_FOLDER=\"/data1/Games/combatris/combatris/assets/\" -I/usr/include/SDL2 -I../combatris/combatris -I../combatris/src -I../external/catch/src/catch/single_include/catch2 -Wall -Wextra -Werror -pedantic -std=c++1z  -Wall -Wextra -Werror -pedantic -std=c++1z -g -g -MD -MT combatris/CMakeFiles/combatris.dir/src/combatris.cpp.o -MF combatris/CMakeFiles/combatris.dir/src/combatris.cpp.o.d -o combatris/CMakeFiles/combatris.dir/src/combatris.cpp.o -c ../combatris/src/combatris.cpp
../combatris/src/combatris.cpp: In member function ‘void Combatris::Play()’:
../combatris/src/combatris.cpp:198:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
  198 |             if (SDL_IsGameController(event.jbutton.which) == 0) {
      |             ^~
../combatris/src/combatris.cpp:202:11: note: here
  202 |           case SDL_CONTROLLERDEVICEADDED:
      |           ^~~~
../combatris/src/combatris.cpp:206:33: error: this statement may fall through [-Werror=implicit-fallthrough=]
  206 |             event.cbutton.which = event.jbutton.which;
      |             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../combatris/src/combatris.cpp:207:11: note: here
  207 |           case SDL_CONTROLLERDEVICEREMOVED:
      |           ^~~~
cc1plus: all warnings being treated as errors
[28/63] Building CXX object combatris/CMakeFiles/combatris.dir/src/utility/fonts.cpp.o
FAILED: combatris/CMakeFiles/combatris.dir/src/utility/fonts.cpp.o 
/usr/bin/c++  -DASSETS_FOLDER=\"/data1/Games/combatris/combatris/assets/\" -I/usr/include/SDL2 -I../combatris/combatris -I../combatris/src -I../external/catch/src/catch/single_include/catch2 -Wall -Wextra -Werror -pedantic -std=c++1z  -Wall -Wextra -Werror -pedantic -std=c++1z -g -g -MD -MT combatris/CMakeFiles/combatris.dir/src/utility/fonts.cpp.o -MF combatris/CMakeFiles/combatris.dir/src/utility/fonts.cpp.o.d -o combatris/CMakeFiles/combatris.dir/src/utility/fonts.cpp.o -c ../combatris/src/utility/fonts.cpp
../combatris/src/utility/fonts.cpp: In member function ‘TTF_Font* utility::Fonts::Get(const utility::Font&) const’:
../combatris/src/utility/fonts.cpp:47:17: error: catching polymorphic type ‘class std::out_of_range’ by value [-Werror=catch-value=]
   47 |   } catch (std::out_of_range) {
      |                 ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[32/63] Building CXX object combatris/CMakeFiles/combatris.dir/src/game/tetrion.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:27: build] Error 1
`

**Comment by drpatrik** [comment]
Thanks. I installed gcc 9.2.0_1 and fixed the code so it compiles cleanly without warnings.

**Comment by drpatrik** [comment]
The alias warning should also be fixed now as well.
